# # Somente a API, o banco de dados está em outro lugar.
# services:
#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     networks:
#       default: null
#     ports:
#       - mode: ingress
#         target: 3333
#         published: '3333'
#         protocol: tcp
#     restart: on-failure:5
#     volumes:
#       - type: bind
#         source: .\src
#         target: /usr/src/app/src
#         bind:
#           create_host_path: true
# networks:
#   default:
#     name: ecoroute-default

# ---------------------------------------------------

# API e banco de dados em um único arquivo.
services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    networks:
      - ecoroute-network
    depends_on:
      - database
    volumes:
      - ./src:/usr/src/app/src
  database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecoroute
    networks:
      - ecoroute-network

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
networks:
  ecoroute-network:
    driver: bridge
volumes:
  pgdata:
